#headles service for postgres
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: devboard
spec:
  clusterIP: None 
  selector:
    app: devboard-postgres
  ports:
  - protocol: TCP
    port: 5432 # service ke leye
    targetPort: 5432 # pod ka port
      
